### PR TITLE
Fix comparison of ScalarFunctionConstantNotZero

### LINKED ISSUE #2189: test_model_ScalarFunctionConstantNotZero not working for non-isbits type
The following test fails
https://github.com/jump-dev/MathOptInterface.jl/blob/a93d14d2d05d433830a4ead3233d127d4e9101fa/src/Test/test_model.jl#L745-L773
because
```julia
julia> T = BigFloat
BigFloat

julia> e1 = MOI.ScalarFunctionConstantNotZero{T, MOI.ScalarAffineFunction{T}, MOI.EqualTo{T}}(zero(T))
MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.EqualTo{BigFloat}}(0.0)

julia> e2 = MOI.ScalarFunctionConstantNotZero{T, MOI.ScalarAffineFunction{T}, MOI.EqualTo{T}}(zero(T))
MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.EqualTo{BigFloat}}(0.0)

julia> e1 == e2
false
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2189

### CODE REVIEW

File: src/constraints.jl [hunk 1]
```diff
@@ -73,6 +73,13 @@ struct ScalarFunctionConstantNotZero{T,F,S} <: Exception
     constant::T
 end
 
+function Base.:(==)(
+    x::ScalarFunctionConstantNotZero{T,F,S},
+    y::ScalarFunctionConstantNotZero{T,F,S},
+) where {T,F,S}
+    return x.constant == b.constant
```
Comment (blegat) [inline src/constraints.jl:80]:
```suggestion
    return x.constant == y.constant
```

**Review by blegat — APPROVED** [review]
