### PR TITLE
Fix modifications in bridge_optimizer

### LINKED ISSUE #1603: Bridges throw wrong errors during modification
Found during https://github.com/jump-dev/SCS.jl/pull/219

```Julia
optimizer = SCS.Optimizer()
MOI.set(optimizer, MOI.Silent(), true)
model = MOI.Bridges.full_bridge_optimizer(
    MOI.Utilities.CachingOptimizer(
        MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
        optimizer,
    ),
    Float64,
)
julia> MOI.Test.test_modification_set_function_single_variable(model, MOI.Test.Config())
Test Failed at /Users/oscar/.julia/dev/MathOptInterface/src/Test/test_modification.jl:29
  Expression: MOI.set(model, MOI.ConstraintFunction(), c, y)
    Expected: MathOptInterface.SettingVariableIndexNotAllowed()
      Thrown: MathOptInterface.SetAttributeNotAllowed{MathOptInterface.ConstraintFunction}(MathOptInterface.ConstraintFunction(), "")
ERROR: There was an error during testing
```

```Julia
optimizer = SCS.Optimizer()
MOI.set(optimizer, MOI.Silent(), true)
model = MOI.Bridges.full_bridge_optimizer(
    MOI.Utilities.CachingOptimizer(
        MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
        optimizer,
    ),
    Float64,
)
julia> MOI.Test.test_objective_incorrect_modifications(model, MOI.Test.Config())
Test Failed at /Users/oscar/.julia/dev/MathOptInterface/src/Test/test_objective.jl:539
  Expression: MOI.set(model, MOI.ConstraintSet(), c, MOI.LessThan(1.0))
    Expected: ArgumentError
  No exception thrown
ERROR: There was an error during testing
```

### PR DESCRIPTION
**Pull request by odow**
Closes #1603

### CODE REVIEW

**Comment by odow** [comment]
@blegat what's this `set` doing?
https://github.com/jump-dev/MathOptInterface.jl/blob/ddbb343858245cf562da4edfc921594a734c8900/test/Bridges/Constraint/functionize.jl#L30

Do we ever need to modify a `VariableIndex` `ConstraintFunction` in the context of bridges? Or is this just something that should have been caught earlier?

File: src/Bridges/bridge_optimizer.jl [hunk 1]
```diff
@@ -1241,6 +1244,42 @@ function MOI.supports(
...
 end
 
+function _set_substituted(
+    b::AbstractBridgeOptimizer,
+    attr::MOI.ConstraintSet,
+    ci::MOI.ConstraintIndex{F,S},
+    value,
+) where {F,S}
+    if !(value isa S)
+        throw(ArgumentError("Invalid type when setting ConstraintSet."))
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1254]: It doesn't seem to be the right place for this. MOIU.Model also does not have the right error:
```julia
julia> model = MOI.Utilities.Model{Float64}()
MOIU.Model{Float64}

julia> b = MOI.Bridges.full_bridge_optimizer(model, Float64)
MOIB.LazyBridgeOptimizer{MOIU.Model{Float64}}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model MOIU.Model{Float64}

julia> x = MOI.add_variable(b)
MathOptInterface.VariableIndex(1)

julia> MOI.add_constraint(model, x, MOI.EqualTo(0.0))
MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.EqualTo{Float64}}(1)

julia> MOI.set(b, MOI.ConstraintSet(), x, MOI.LessThan(1.0))
ERROR: ArgumentError: `supports` is not defined for MathOptInterface.ConstraintSet(), it is only defined for attributes such that `is_copyable` returns `true`.
Stacktrace:
 [1] supports_fallback(#unused#::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, #unused#::Type{MathOptInterface.VariableIndex})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:249
 [2] supports(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, args::Type)
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:224
 [3] throw_set_error_fallback(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, index::MathOptInterface.VariableIndex, value::MathOptInterface.LessThan{Float64}; error_if_supported::MathOptInterface.SetAttributeNotAllowed{MathOptInterface.ConstraintSet})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:506
 [4] throw_set_error_fallback(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, index::MathOptInterface.VariableIndex, value::MathOptInterface.LessThan{Float64})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:506
 [5] set(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, ::MathOptInterface.ConstraintSet, ::MathOptInterface.VariableIndex, ::MathOptInterface.LessThan{Float64})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:481
 [6] top-level scope
   @ REPL[14]:1

julia> MOI.set(model, MOI.ConstraintSet(), x, MOI.LessThan(1.0))
ERROR: ArgumentError: `supports` is not defined for MathOptInterface.ConstraintSet(), it is only defined for attributes such that `is_copyable` returns `true`.
Stacktrace:
 [1] supports_fallback(#unused#::MathOptInterface.Utilities.Model{Float64}, attr::MathOptInterface.ConstraintSet, #unused#::Type{MathOptInterface.VariableIndex})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:249
 [2] supports(model::MathOptInterface.Utilities.Model{Float64}, attr::MathOptInterface.ConstraintSet, args::Type)
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:224
 [3] throw_set_error_fallback(model::MathOptInterface.Utilities.Model{Float64}, attr::MathOptInterface.ConstraintSet, index::MathOptInterface.VariableIndex, value::MathOptInterface.LessThan{Float64}; error_if_supported::MathOptInterface.SetAttributeNotAllowed{MathOptInterface.ConstraintSet})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:506
 [4] throw_set_error_fallback(model::MathOptInterface.Utilities.Model{Float64}, attr::MathOptInterface.ConstraintSet, index::MathOptInterface.VariableIndex, value::MathOptInterface.LessThan{Float64})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:506
 [5] set(::MathOptInterface.Utilities.Model{Float64}, ::MathOptInterface.ConstraintSet, ::MathOptInterface.VariableIndex, ::MathOptInterface.LessThan{Float64})
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:481
 [6] top-level scope
   @ REPL[15]:1
```

Comment (blegat) [reply src/Bridges/bridge_optimizer.jl:1254]: Why not add a `throw_set_error_fallback` method so that we fix this for all model at the same time ?

File: src/Bridges/bridge_optimizer.jl [hunk 2]
```diff
@@ -1241,6 +1244,42 @@ function MOI.supports(
...
+function _set_substituted(
+    b::AbstractBridgeOptimizer,
+    attr::MOI.ConstraintFunction,
+    ci::MOI.ConstraintIndex{F,S},
+    value,
+) where {F,S}
+    if F == MOI.VariableIndex
+        throw(MOI.SettingVariableIndexNotAllowed())
+    elseif !(value isa F)
+        throw(ArgumentError("Invalid type when setting ConstraintFunction."))
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1273]: Again, this should be in `throw_set_error_fallback` method so that we fix this for all model at the same time ?` In fact, I don't understand how this can be called since the signature of `MOI.set` of `AbstractBridgeOptimizer` ensures that the set has the same type.

File: src/Bridges/bridge_optimizer.jl [hunk 3]
```diff
@@ -1241,6 +1244,42 @@ function MOI.supports(
...
+end
+
+function _set_substituted(
+    b::AbstractBridgeOptimizer,
+    attr::MOI.ConstraintFunction,
+    ci::MOI.ConstraintIndex{F,S},
+    value,
+) where {F,S}
+    if F == MOI.VariableIndex
+        throw(MOI.SettingVariableIndexNotAllowed())
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1271]: Why not adding a method
```julia
function MOI.set(
     b::AbstractBridgeOptimizer,
    attr::MOI.ConstraintFunction,
    ci::MOI.ConstraintIndex{MOI.SingleVariable},
    func::MOI.SingleVariable,
)
```
I prefer keeping only one `_set_substituted` and doing the dispatch at the `MOI.set` level.

File: src/Bridges/bridge_optimizer.jl (hunk 2 above)
Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1273]: Because there's this fallback method for everything
https://github.com/jump-dev/MathOptInterface.jl/blob/ddbb343858245cf562da4edfc921594a734c8900/src/Bridges/bridge_optimizer.jl#L1259-L1267

File: src/Bridges/bridge_optimizer.jl (hunk 1 above)
Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1254]: This is wrong because you're using `x` instead of the constraint index.

Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1254]:
```Julia
julia> model = MOI.Utilities.Model{Float64}()
MOIU.Model{Float64}

julia> b = MOI.Bridges.full_bridge_optimizer(model, Float64)
MOIB.LazyBridgeOptimizer{MOIU.Model{Float64}}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model MOIU.Model{Float64}

julia> x = MOI.add_variable(b)
MathOptInterface.VariableIndex(1)

julia> c = MOI.add_constraint(model, x, MOI.EqualTo(0.0))
MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.EqualTo{Float64}}(1)

julia> MOI.set(b, MOI.ConstraintSet(), c, MOI.LessThan(1.0))
ERROR: ArgumentError: Invalid type when setting ConstraintSet.
Stacktrace:
 [1] _set_substituted(b::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, ci::MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.EqualTo{Float64}}, value::MathOptInterface.LessThan{Float64})
   @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:1254
 [2] set(b::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.Model{Float64}}, attr::MathOptInterface.ConstraintSet, ci::MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.EqualTo{Float64}}, value::MathOptInterface.LessThan{Float64})
   @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:1304
 [3] top-level scope
   @ REPL[11]:1
```

File: src/Bridges/bridge_optimizer.jl [hunk 4]
```diff
@@ -1143,8 +1147,11 @@ function MOI.set(
     b::AbstractBridgeOptimizer,
     attr::MOI.ConstraintSet,
     ci::MOI.ConstraintIndex{MOI.VariableIndex,S},
-    value::S,
+    value,
 ) where {S<:MOI.AbstractScalarSet}
+    if typeof(value) != S
+        throw(ArgumentError("Invalid type when setting ConstraintSet."))
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1153]: Is the plan to add this in every model implementing MOI? Why not fixing it for all of them at the same time in `src/attributes.jl`

Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1153]: Because generic fallbacks get in the way.

**Review by blegat — APPROVED** [review]
