### PR TITLE
[FileFormats.LP] add support for indicator constraints

### LINKED ISSUE #2354: [FileFormats.LP] support indicator constraints
The following works:
```julia
julia> model=Model();
julia> @variable(model,x);
julia> @variable(model,y,Bin);
julia> @constraint(model, y => {x == 0});
julia> write_to_file(model,"test.lp")
```
However if the indicator constraint is changed to `@constraint(model, !y => {x == 0})`, writing the LP file fails:
```julia
ERROR: Unable to use IndicatorToMILPBridge because element 2 in the function has a non-finite domain: 0.0 + 1.0 MOI.VariableIndex(2)
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2354

### CODE REVIEW

File: test/FileFormats/LP/LP.jl [hunk 1]
```diff
@@ -976,6 +1011,55 @@ function test_read_variable_bounds()
...
+    Binary
+    z
+    End
+    """
+    return
+end
+
+function test_VectorAffineFunction_SOS()
+    model = MOI.FileFormats.LP.Model()
+    x = MOI.add_variables(3)
```
Comment (odow) [inline test/FileFormats/LP/LP.jl:1051]:
```suggestion
    x = MOI.add_variables(model, 3)
```

File: test/FileFormats/LP/LP.jl [hunk 2]
```diff
@@ -976,6 +1011,55 @@ function test_read_variable_bounds()
...
+    """
+    return
+end
+
+function test_VectorAffineFunction_SOS()
+    model = MOI.FileFormats.LP.Model()
+    x = MOI.add_variables(model, 3)
+    f = MOI.Utilities.operate(vcat, Float64, (1.0 .* x)...)
+    for set in (MOI.SOS1([1.0, 2.0, 3.0]), MOI.SOS2([1.0, 2.0, 3.0]))
+        @test !MOI.supports_constraint(model, f, set)
```
Comment (odow) [inline test/FileFormats/LP/LP.jl:1054]:
```suggestion
        @test !MOI.supports_constraint(model, typeof(f), typeof(set))
```

File: test/FileFormats/LP/LP.jl [hunk 3]
```diff
@@ -976,6 +1011,55 @@ function test_read_variable_bounds()
...
+end
+
+function test_VectorAffineFunction_SOS()
+    model = MOI.FileFormats.LP.Model()
+    x = MOI.add_variables(model, 3)
+    f = MOI.Utilities.operate(vcat, Float64, (1.0 .* x)...)
+    for set in (MOI.SOS1([1.0, 2.0, 3.0]), MOI.SOS2([1.0, 2.0, 3.0]))
+        @test !MOI.supports_constraint(model, typeof(f), typeof(set))
+        @test_throws(
+            MOI.UnsupportedConstraint{typeof(f),type(set)},
```
Comment (odow) [inline test/FileFormats/LP/LP.jl:1056]:
```suggestion
            MOI.UnsupportedConstraint{typeof(f),typeof(set)},
```

File: src/FileFormats/LP/LP.jl [hunk 4]
```diff
@@ -338,6 +364,63 @@ function _write_constraint(
...
+) where {T,F<:Union{MOI.VectorOfVariables,MOI.VectorAffineFunction{T}},A,S}
+    func = MOI.get(model, MOI.ConstraintFunction(), index)
+    set = MOI.get(model, MOI.ConstraintSet(), index)
+    if write_name
+        print(io, MOI.get(model, MOI.ConstraintName(), index), ": ")
+    end
+    z, f = MOI.Utilities.scalarize(func)
+    flag = A == MOI.ACTIVATE_ON_ONE ? 1 : 0
+    _write_function(io, model, z, variable_names; print_one = false)
+    # print(io, variable_names[z],
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:417]:
```suggestion
```
