### PR TITLE
[Bridges] fix getting ConstraintPrimal if Variable bridges are present

### LINKED ISSUE #2384: Failure with CachingOptimizer
This seems like a bug in `CachingOptimizer`
```julia
using Test
import MathOptInterface as MOI
import CSDP

function tests(cache)
    model = MOI.instantiate(CSDP.Optimizer, with_bridge_type = Float64)
    if cache
        model = MOI.Utilities.CachingOptimizer(
            MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
            model,
        )
    end
    MOI.set(model, MOI.Silent(), true)
    MOI.Test.runtests(
      model,
      MOI.Test.Config(
          rtol = 1e-3,
          atol = 1e-3,
          exclude = Any[
              MOI.ConstraintBasisStatus,
              MOI.VariableBasisStatus,
              MOI.ObjectiveBound,
              MOI.SolverVersion,
          ],
      ),
      include = Regex[
          r"test_variable_solve_with_lowerbound$",
          r"test_modification_delete_variables_in_a_batch$",
      ],
    )
end

@testset "$cache" for cache in [false, true]
   tests(cache)
end
```
produces
```
Test Summary: | Pass  Total  Time
false         |   18     18  0.9s
test_modification_delete_variables_in_a_batch: Test Failed at /home/blegat/.julia/packages/MathOptInterface/vrZOD/src/Test/test_modification.jl:827
  Expression: isapprox(MOI.get(model, MOI.ObjectiveValue()), T(2), config)
   Evaluated: isapprox(6.0, 2.0, MathOptInterface.Test.Config{Float64}(0.001, 0.001, MathOptInterface.OPTIMAL, MathOptInterface.INFEASIBLE, Any[MathOptInterface.ConstraintBasisStatus, MathOptInterface.VariableBasisStatus, MathOptInterface.ObjectiveBound, MathOptInterface.SolverVersion]))

Stacktrace:
 [1] macro expansion
   @ ~/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] test_modification_delete_variables_in_a_batch(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, config::MathOptInterface.Test.Config{Float64})
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/vrZOD/src/Test/test_modification.jl:827
 [3] macro expansion
   @ ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:272 [inlined]
 [4] macro expansion
   @ ~/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [5] runtests(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, config::MathOptInterface.Test.Config{Float64}; include::Vector{Regex}, exclude::Vector{String}, warn_unsupported::Bool, verbose::Bool, exclude_tests_after::VersionNumber)
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:267
test_variable_solve_with_lowerbound: Test Failed at /home/blegat/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:462
  Expression: isapprox(MOI.get(model, MOI.ConstraintPrimal(), index), solution_value, config)
   Evaluated: isapprox(9.973062820023415e-9, 1.0, MathOptInterface.Test.Config{Float64}(0.001, 0.001, MathOptInterface.OPTIMAL, MathOptInterface.INFEASIBLE, Any[MathOptInterface.ConstraintBasisStatus, MathOptInterface.VariableBasisStatus, MathOptInterface.ObjectiveBound, MathOptInterface.SolverVersion]))

Stacktrace:
 [1] macro expansion
   @ ~/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:672 [inlined]
 [2] _test_model_solution(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, config::MathOptInterface.Test.Config{Float64}; objective_value::Float64, variable_primal::Vector{Tuple{MathOptInterface.VariableIndex, Float64}}, constraint_primal::Vector{Tuple{MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}, Float64}}, constraint_dual::Vector{Tuple{MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}, Float64}})
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:462
 [3] _test_model_solution
   @ ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:427 [inlined]
 [4] test_variable_solve_with_lowerbound(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, config::MathOptInterface.Test.Config{Float64})
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/vrZOD/src/Test/test_variable.jl:244
 [5] macro expansion
   @ ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:272 [inlined]
 [6] macro expansion
   @ ~/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [7] runtests(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, config::MathOptInterface.Test.Config{Float64}; include::Vector{Regex}, exclude::Vector{String}, warn_unsupported::Bool, verbose::Bool, exclude_tests_after::VersionNumber)
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/vrZOD/src/Test/Test.jl:267
Test Summary:                                   | Pass  Fail  Total  Time
true                                            |   16     2     18  0.7s
  test_modification_delete_variables_in_a_batch |    7     1      8  0.7s
  test_variable_solve_with_lowerbound           |    9     1     10  0.0s
ERROR: LoadError: Some tests did not pass: 16 passed, 2 failed, 0 errored, 0 broken.
in expression starting at /home/blegat/.julia/dev/CSDP/test/bug2.jl:33
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2384

### CODE REVIEW

File: src/Bridges/bridge_optimizer.jl [hunk 1]
```diff
@@ -1496,6 +1496,23 @@ function MOI.get(
...
+    attr::MOI.ConstraintPrimal,
+    ci::MOI.ConstraintIndex,
+)
+    if is_bridged(b, ci)
+        MOI.throw_if_not_valid(b, ci)
+        return call_in_context(MOI.get, b, ci, attr)
+    elseif !Variable.has_bridges(Variable.bridges(b))
+        return MOI.get(b.model, attr, ci)
+    else
+        # Get the fallback, because the function might contain bridged
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1510]: I don't see why this would be an issue, let me take a look

Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1510]: Take a look at https://github.com/jump-dev/MathOptInterface.jl/issues/2384#issuecomment-1880349485. Perhaps I'm missing something about how the substitutions should work.

Comment (blegat) [reply src/Bridges/bridge_optimizer.jl:1510]: Thanks, that reduced example should help

Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1510]: It's an issue for the same reason as 
https://github.com/jump-dev/MathOptInterface.jl/blob/79c19e09f024de009238a7b78af7cf355c62cc45/src/Bridges/bridge_optimizer.jl#L1380-L1403

Except that we can't call `unbridged_constraint_function` because the return from `MOI.get` is just a scalar, so we don't know what contributed to the primal and what was moved to the set.

**Comment by odow** [comment]
@blegat I've added a test. This is a bug fix, so I'd like to get it into #2399. I can leave you to figure out if there is a more elegant bug fix?

File: src/Bridges/bridge_optimizer.jl (hunk 1 above)
Comment (blegat) [reply src/Bridges/bridge_optimizer.jl:1510]: Ok, I see what's the issue. Because it's a scalar constraint, `normalize_and_add_constraint` moves the constant to the set so it does not contribute to `ConstraintPrimal` anymore. Could you add a comment explaining that this is due to this ? Then it's good to merge

File: src/Bridges/bridge_optimizer.jl [hunk 2]
```diff
@@ -1496,6 +1496,23 @@ function MOI.get(
     return unbridged_function(b, func)
 end
 
+function MOI.get(
+    b::AbstractBridgeOptimizer,
+    attr::MOI.ConstraintPrimal,
+    ci::MOI.ConstraintIndex,
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:1502]: We could restrict this to scalar functions and sets, there should be no issue with vector ones

Comment (odow) [reply src/Bridges/bridge_optimizer.jl:1502]: Ah yes, cool cool. I'll make the change

**Review by blegat — APPROVED** [review]
