### PR TITLE
Fix support for external sets in loadfromstring

### LINKED ISSUE #2175: Bridge tests outside of MOI
Using `MOI.Bridges.runtests` is not feasible with a set defined outside MOI because of
https://github.com/jump-dev/MathOptInterface.jl/blob/9a9188a15e0ccdf7d9e7a44dfd7a9f6bdf33229a/src/Utilities/parser.jl#L336
and
https://github.com/jump-dev/MathOptInterface.jl/blob/9a9188a15e0ccdf7d9e7a44dfd7a9f6bdf33229a/src/Utilities/parser.jl#L365

### PR DESCRIPTION
**Pull request by odow**
Closes #2175

### CODE REVIEW

File: test/FileFormats/SDPA/SDPA.jl [hunk 1]
```diff
@@ -10,6 +10,7 @@ using Test
 
 import MathOptInterface as MOI
 import MathOptInterface.Utilities as MOIU
+
```
Comment (odow) [inline test/FileFormats/SDPA/SDPA.jl:13]:
```suggestion
```

**Comment by odow** [comment]
This is technically breaking if the is given as `MathOptInterface.XYZ()` and MathOptInterface is not a defined symbol in the current scope (e.g., because it was `import MathOptInterface as MOI`). 

Let's see if `solver-tests` complains: https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5075528679

**Comment by odow** [comment]
HiGHS failed, https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5075528679/jobs/9116842487, so I guess I need to fix this properly.

**Review by blegat — APPROVED** [review]
