### PR TITLE
[Bridges] fix deleting variable with constraint bridges

### LINKED ISSUE #2817: Deletion bug in bridges
```Julia
julia> import MathOptInterface as MOI

julia> MOI.Utilities.@model(
           MyModel,
           (),
           (),
           (MOI.Nonnegatives,),
           (),
           (),
           (),
           (),
           (MOI.VectorAffineFunction,)
       );

julia> function MOI.supports_constraint(
           ::MyModel,
           ::Type{MOI.VariableIndex},
           ::Type{S},
       ) where {S<:MOI.AbstractScalarSet}
           return false
       end

julia> model = MOI.instantiate(MyModel{Float64}; with_bridge_type = Float64);

julia> x, _ = MOI.add_constrained_variable(model, MOI.Interval(0.0, 1.0));

julia> MOI.delete(model, x)
ERROR: The index MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, MathOptInterface.HyperRectangle{Float64}}(-1) is invalid. Note that an index becomes invalid after it has been deleted.
Stacktrace:
  [1] throw_if_not_valid
    @ ~/.julia/dev/MathOptInterface/src/indextypes.jl:116 [inlined]
  [2] delete(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, ci::MathOptInterface.ConstraintIndex{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:668
  [3] delete
    @ ~/.julia/dev/MathOptInterface/src/Bridges/Constraint/bridges/IntervalToHyperRectangleBridge.jl:98 [inlined]
  [4] #11
    @ ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:690 [inlined]
  [5] call_in_context(map::MathOptInterface.Bridges.Variable.Map, bridge_index::Int64, f::MathOptInterface.Bridges.var"#11#12"{…})
    @ MathOptInterface.Bridges.Variable ~/.julia/dev/MathOptInterface/src/Bridges/Variable/map.jl:621
  [6] call_in_context(map::MathOptInterface.Bridges.Variable.Map, ci::MathOptInterface.ConstraintIndex{…}, f::Function)
    @ MathOptInterface.Bridges.Variable ~/.julia/dev/MathOptInterface/src/Bridges/Variable/map.jl:652
  [7] delete(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, ci::MathOptInterface.ConstraintIndex{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:687
  [8] _delete_variables_in_variables_constraints(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, vis::Vector{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:531
  [9] delete(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, vi::MathOptInterface.VariableIndex)
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:636
 [10] top-level scope
    @ REPL[258]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2817 

I don't think this is the proper fix. But passes the test. I want to run `solver-tests` with it if CI is green

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17026926756

### CODE REVIEW

**Comment by odow** [comment]
CDDLib failure seems related, so the logic does need to be more complicated.

image

**Comment by odow** [comment]
CDDLib failure is
```Julia
julia> MOI.Utilities.@model(
           Model2817b,
           (),
           (MOI.LessThan,),
           (),
           (),
           (),
           (MOI.ScalarAffineFunction,),
           (),
           ()
       );

julia> function MOI.supports_constraint(
           ::Model2817b,
           ::Type{MOI.VariableIndex},
           ::Type{S},
       ) where {S<:MOI.AbstractScalarSet}
           return false
       end

julia> function main()
           model = MOI.instantiate(Model2817b{Float64}; with_bridge_type = Float64)
           y, _ = MOI.add_constrained_variables(model, MOI.Nonpositives(1))
           MOI.delete(model, y)
       end
main (generic function with 1 method)

julia> main()
ERROR: The index MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.LessThan{Float64}}(1) is invalid. Note that an index becomes invalid after it has been deleted.
Stacktrace:
  [1] throw_if_not_valid
    @ ~/.julia/dev/MathOptInterface/src/indextypes.jl:116 [inlined]
  [2] get(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, attr::MathOptInterface.ConstraintFunction, ci::MathOptInterface.ConstraintIndex{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:1457
  [3] _broadcast_getindex_evalf
    @ ./broadcast.jl:709 [inlined]
  [4] _broadcast_getindex
    @ ./broadcast.jl:682 [inlined]
  [5] getindex
    @ ./broadcast.jl:636 [inlined]
  [6] copy
    @ ./broadcast.jl:942 [inlined]
  [7] materialize
    @ ./broadcast.jl:903 [inlined]
  [8] get(model::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, attr::MathOptInterface.ConstraintFunction, bridge::MathOptInterface.Bridges.Constraint.ScalarizeBridge{…})
    @ MathOptInterface.Bridges.Constraint ~/.julia/dev/MathOptInterface/src/Bridges/Constraint/bridges/ScalarizeBridge.jl:127
  [9] (::MathOptInterface.Bridges.var"#3#4"{…})(bridge::MathOptInterface.Bridges.Constraint.ScalarizeBridge{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:324
 [10] (::MathOptInterface.Bridges.var"#1#2"{MathOptInterface.Bridges.LazyBridgeOptimizer{…}, MathOptInterface.ConstraintIndex{…}, MathOptInterface.Bridges.var"#3#4"{…}})()
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:309
 [11] call_in_context(map::MathOptInterface.Bridges.Variable.Map, bridge_index::Int64, f::MathOptInterface.Bridges.var"#1#2"{…})
    @ MathOptInterface.Bridges.Variable ~/.julia/dev/MathOptInterface/src/Bridges/Variable/map.jl:621
 [12] call_in_context
    @ ~/.julia/dev/MathOptInterface/src/Bridges/Variable/map.jl:652 [inlined]
 [13] call_in_context(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, ci::MathOptInterface.ConstraintIndex{…}, f::MathOptInterface.Bridges.var"#3#4"{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:306
 [14] call_in_context
    @ ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:321 [inlined]
 [15] get(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, attr::MathOptInterface.ConstraintFunction, ci::MathOptInterface.ConstraintIndex{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:1465
 [16] _delete_variables_in_vector_of_variables_constraint(b::MathOptInterface.Bridges.LazyBridgeOptimizer{…}, vis::Vector{…}, ci::MathOptInterface.ConstraintIndex{…})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:491
 [17] _delete_variables_in_variables_constraints(b::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.GenericModel{…}}, vis::Vector{MathOptInterface.VariableIndex})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:545
 [18] delete(b::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.GenericModel{…}}, vis::Vector{MathOptInterface.VariableIndex})
    @ MathOptInterface.Bridges ~/.julia/dev/MathOptInterface/src/Bridges/bridge_optimizer.jl:613
 [19] main()
    @ Main ./REPL[453]:4
 [20] top-level scope
    @ REPL[454]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by odow** [comment]
The underlying cause is the same as https://github.com/jump-dev/MathOptInterface.jl/issues/2696

We don't really have a chain-of-custody to discriminate constraints that were added by the user at the top level from constraints added by bridges, unless we walk all the bridges to check.
```julia
julia> MOI.Utilities.@model(
           Model2817b,
           (),
           (MOI.LessThan,),
           (),
           (),
           (),
           (MOI.ScalarAffineFunction,),
           (),
           ()
       );

julia> function MOI.supports_constraint(
           ::Model2817b,
           ::Type{MOI.VariableIndex},
           ::Type{S},
       ) where {S<:MOI.AbstractScalarSet}
           return false
       end

julia> model = MOI.instantiate(Model2817b{Float64}; with_bridge_type = Float64);

julia> y, _ = MOI.add_constrained_variables(model, MOI.Nonpositives(1));

julia> ci = MOI.ConstraintIndex{MOI.VariableIndex,MOI.LessThan{Float64}}(1)
MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.LessThan{Float64}}(1)

julia> MOI.is_valid(model, ci)
true
```

**Comment by odow** [comment]
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17029443959

**Comment by odow** [comment]
Okay. I think that's everything passing tests at least. Now to document what exactly I did...

**Comment by odow** [comment]
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17031397524

File: src/Bridges/bridge_optimizer.jl [hunk 1]
```diff
@@ -489,49 +515,90 @@ function _delete_variables_in_vector_of_variables_constraint(
...
-            if i !== nothing
-                if MOI.supports_dimension_update(S)
-                    call_in_context(MOI.delete, b, ci, IndexInVector(i))
-                else
-                    MOI.Utilities.throw_delete_variable_in_vov(vi)
-                end
-            end
+        return
+    end
+    variables = copy(func.variables)
```
Comment (odow) [inline src/Bridges/bridge_optimizer.jl]: I could revert the indentation change for this one. I just moved the copy after the first `vis == func.variables` check because that's a common case we can skip the copy for.

File: src/Bridges/bridge_optimizer.jl [hunk 2]
```diff
@@ -489,49 +515,90 @@ function _delete_variables_in_vector_of_variables_constraint(
...
+    cache::Dict{Any,Any},
+    ci::MOI.ConstraintIndex{F,S},
+) where {F,S}
+    ret = get!(cache, (F, S)) do
+        list = MOI.ConstraintIndex{F,S}[]
+        for bridge in values(c_map)
+            append!(list, MOI.get(bridge, MOI.ListOfConstraintIndices{F,S}()))
+        end
+        return list
+    end
```
Comment (odow) [inline src/Bridges/bridge_optimizer.jl]:
```suggestion
    end::Vector{MOI.ConstraintIndex{F,S}}
```

File: src/Bridges/bridge_optimizer.jl [hunk 3]
```diff
@@ -476,6 +476,32 @@ function MOI.is_valid(
...
+            # effects because bridges need this to be "true" so that they can
+            # query attributes of the constraint from `b`.
+            #
+            # In most cases a false positive doesn't matter, because we really
+            # do support querying stuff about it. And also the user needs some
+            # way of obtaining the correct index, which they won't have except
+            # by luck/enumeration.
+            #
+            # The main place that this is problematic is when we come to delete
+            # constraints, and particular VariableIndex constraints, because we
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl]:
```suggestion
            # constraints, and in particular VariableIndex constraints, because we
```

File: src/Bridges/bridge_optimizer.jl [hunk 4]
```diff
@@ -504,34 +530,81 @@ function _delete_variables_in_vector_of_variables_constraint(
...
+    )
+
+The point of this function is to delete constraints associated with the
+variables in `vis`.
+
+## Warning
+
+Because of the false positive potential in
+`is_valid(::AbstractBridgeOptimizer, MOI.ConstraintIndex)`, we need to ensure
+that we delete constraints only if they were not added by a different constraint
```
Comment (blegat) [inline src/Bridges/bridge_optimizer.jl:582]: What do you mean by different bridge ? It seems to me that if a bridge tries to delete a variable, now it won't delete any constraint created on that variable. So we are kind of assuming that the bridges can't rely on the fact that when they delete variables, the constraint on this variable won't be delete automatically, while the user can expect this behavior

**Comment by blegat** [comment]
I think we should also clarify in the docstring of `delete` for bridges that they should delete all constraints by themself and not rely on the automatic deletion of variable-constraints that are deleted by the variables.

File: src/Bridges/bridge_optimizer.jl (hunk 4 above)
Comment (odow) [reply src/Bridges/bridge_optimizer.jl:582]: Hmm. Maybe I need to check this. I thought if a bridge deletes a variable it will, by the logic in this function, delete the related constraints.

**Comment by odow** [comment]
> for bridges that they should delete all constraints by themself and not rely on the automatic deletion of variable-constraints that are deleted by the variables

I don't think this is necessary. Do you have an example that fails? If a bridge has, for example, added a binary variable, the ZeroOne constraint can't exist if the variable has been deleted.

**Comment by odow** [comment]
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17059980958

File: test/Bridges/bridge_optimizer.jl [hunk 5]
```diff
@@ -1463,6 +1465,111 @@ function test_BridgeRequiresFiniteDomainError()
...
+    @test MOI.is_empty(model)
+    @test MOI.is_empty(inner)
+    @test isempty(model.constraint_map)
+    return
+end
+
+MOI.Utilities.@model(
+    Model2817c,
+    (),
+    (MOI.GreaterThan, MOI.LessThan,),
```
Comment (odow) [inline test/Bridges/bridge_optimizer.jl]:
```suggestion
    (MOI.GreaterThan, MOI.LessThan),
```

**Comment by odow** [comment]
Confirmed that it's not necessary, and I've added a test for it.
