### PR TITLE
Fixed unsupported objectives in FileFormats

### LINKED ISSUE #1116: Model Writing Error Messages
Given this model,
```
m = Model()
@variable(m, x)
@objective(m, Min, x^2)
```

The command, `write_to_file(m, "model.lp")` yields,
```
ERROR: MethodError: no method matching write_function(::IOStream, ::MathOptInterface.FileFormats.LP.Model{Float64}, ::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Dict{MathOptInterface.VariableIndex,String})
```

The command, `write_to_file(m, "model.mps")` yields,
```
ERROR: MethodError: no method matching extract_terms(::MathOptInterface.FileFormats.MPS.Model{Float64}, ::Dict{String,Array{Tuple{String,Float64},1}}, ::String, ::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Set{String})
```

Could these messages be improved?  Maybe something like, format X does not support constraint type Y?

### PR DESCRIPTION
**Pull request by egbuck**
Closes #1116

### CODE REVIEW

File: src/Utilities/model.jl [hunk 1]
```diff
@@ -416,7 +416,10 @@ function MOI.supports(
         MOI.ScalarQuadraticFunction{T}}}) where T
     return true
 end
-function MOI.set(model::AbstractModel, ::MOI.ObjectiveFunction, f::MOI.AbstractFunction)
+function MOI.set(model::AbstractModel, attr::MOI.ObjectiveFunction, f::MOI.AbstractFunction)
+    if !MOI.supports(model, attr)
+        throw(MOI.UnsupportedAttribute(attr))
+    end
```
Comment (odow) [inline src/Utilities/model.jl:422]: @blegat how breaking is this? It turns out, even if you said you didn't support it, it would still accept it.
