### PR TITLE
[FileFormats.MPS] Fix to stop writing OBJSENSE by default

### LINKED ISSUE #1806: FileFormats.MPS: add option to not write OBJSENSE
Introduced in https://github.com/jump-dev/MathOptInterface.jl/pull/1391, but broke https://github.com/joaquimg/BilevelJuMP.jl/issues/170.

We should add an option to skip
https://github.com/jump-dev/MathOptInterface.jl/blob/6b50fa0f9e31ef97a06facaad60af7d0b6ae3d2a/src/FileFormats/MPS/MPS.jl#L174-L178
and negate the objective coefficients.

cc @joaquimg

### PR DESCRIPTION
**Pull request by odow**
Closes #1806

### CODE REVIEW

File: src/FileFormats/MPS/MPS.jl [hunk 1]
```diff
@@ -53,10 +54,11 @@ Create an empty instance of FileFormats.MPS.Model.
 Keyword arguments are:
 
  - `warn::Bool=false`: print a warning when variables or constraints are renamed.
+ - `print_objsense::Bool=true`: print the OBJSENSE section when writing
```
Comment (joaquimg) [inline src/FileFormats/MPS/MPS.jl:57]: Default is false

Comment (odow) [inline src/FileFormats/MPS/MPS.jl:57]:
```suggestion
 - `print_objsense::Bool=false`: print the OBJSENSE section when writing
```
