### PR TITLE
Clarify error message in quad_to_soc

### LINKED ISSUE #1259: Clarify error message in quad_to_soc bridge
Running the model
```julia
model = Model(COSMO.Optimizer)  # or model = Model(SCS.Optimizer)
@variable(model, w[1:6]>= 0)
@constraint(model, sum(w) == 1)
@constraint(model, w' * pcov * w == 0.038^2)
@objective(model, Max, pmean' * w)
optimize!(model)
optimal_solution = value.(w)
```
with:
```
pmean = [0.006719140992780818, 0.011577810667787833, 0.01344208119264699, 0.005535719592233162, 0.026922967360723037, 0.00934581295816873]

pcov = [0.018717403832096687 0.005706355121276367 0.006459876807928641 0.0012524618528797894 0.002563861720279623 0.0007671488407868487; 0.005706355121276367 0.006526570285541143 0.004384136499235087 0.0011480135148245983 0.0018044216713121253 0.001154428875412326; 0.006459876807928641 0.004384136499235087 0.0054284300755523115 0.0006596834879959167 0.0016581295100441041 0.0007133949662164625; 0.0012524618528797894 0.0011480135148245983 0.0006596834879959167 0.0026543564006455294 0.00048713871877351897 0.0011206346404939; 0.002563861720279623 0.0018044216713121253 0.0016581295100441041 0.00048713871877351897 0.0023567945429189227 0.00043958950944804554; 0.0007671488407868487 0.001154428875412326 0.0007133949662164625 0.0011206346404939 0.00043958950944804554 0.0020143379751173373]
```
one gets the following error,
```
ERROR: LoadError: The optimizer supports second-order cone constraints and not quadratic constraints but you entered a quadratic constraint of type: `MathOptInterface.ScalarQuadraticFunction{Float64}`-in-`MathOptInterface.GreaterThan{Float64}`. A bridge attempted to transform the quadratic constraint to a second order cone constraint but the constraint is not strongly convex, i.e., the symmetric matrix of quadratic coefficients is not positive definite. Convex constraints that are not strongly convex, i.e. the matrix is positive semidefinite but not positive definite, are not supported yet.
```
However the matrix `pcov` is  positive definite (all eigen values > 0) and the constraint is therefore strongly convex.

### PR DESCRIPTION
**Pull request by odow**
Closes #1259

cc @ASaragga

### CODE REVIEW

File: src/Bridges/Constraint/quad_to_soc.jl [hunk 1]
```diff
@@ -78,18 +78,15 @@ function bridge_constraint(
...
-                " A bridge attempted to transform the quadratic constraint",
-                " to a second order cone constraint but the constraint is",
-                " not strongly convex, i.e., the symmetric matrix of",
-                " quadratic coefficients is not positive definite. Convex",
-                " constraints that are not strongly convex, i.e. the matrix is",
-                " positive semidefinite but not positive definite, are not",
-                " supported yet.",
-            )
+            error("""
+            Unable to transform a quadratic constraint into a second-order cone
```
Comment (blegat) [inline src/Bridges/Constraint/quad_to_soc.jl:82]: "second-order cone" -> "second-order cone constraint" ?

**Review by blegat — APPROVED** [review]
