### PR TITLE
[FileFormats.MOF] fix reading nonlinear objectives only

### LINKED ISSUE #2067: ScalarNonlinearFunction ignored when reading MOF file
using the example from https://github.com/jump-dev/MathOptFormat/blob/master/examples/nlp.mof.json

and reading in with 
```
import JSON, JSONSchema
import MathOptInterface
const MOI = MathOptInterface

file = joinpath(@__DIR__, "nlp.mof.json")

# validate
file_string = read(file, String)
schema = JSONSchema.Schema(JSON.parsefile(MOI.FileFormats.MOF.SCHEMA_PATH))
json = JSON.parse(file_string)
@show JSONSchema.validate(schema, json)
println()

# load/display
model = MOI.FileFormats.Model(format = MOI.FileFormats.FORMAT_MOF)
MOI.read_from_file(model, file)
println(model)
```
I just get an empty model
```
JSONSchema.validate(schema, json) = nothing

Minimize ScalarAffineFunction{Float64}:
 0.0

Subject to:

```

### PR DESCRIPTION
**Pull request by odow**
Closes #2067

### CODE REVIEW

File: test/FileFormats/MOF/MOF.jl [hunk 1]
```diff
@@ -1201,6 +1201,35 @@ function test_parse_constraintname_variable()
...
+}""",
+    )
+    seekstart(io)
+    model = MOF.Model()
+    read!(io, model)
+    block = MOI.get(model, MOI.NLPBlock())
+    @test block isa MOI.NLPBlockData
+    @test block.has_objective
+    MOI.initialize(block.evaluator, Symbol[])
+    @test MOI.eval_objective(block.evaluator, [2.0]) ≈ sinn(2.0)
```
Comment (odow) [inline test/FileFormats/MOF/MOF.jl:1229]:
```suggestion
    @test MOI.eval_objective(block.evaluator, [2.0]) ≈ sin(2.0)
```
