### PR TITLE
[Utilities] fix printing of LaTeX model

### LINKED ISSUE #2140: `{` in string is not filtered in tex output
```Julia
# https://jump.dev/MathOptInterface.jl/stable/tutorials/example/
using GLPK
import MathOptInterface as MOI

optimizer = GLPK.Optimizer()
    c = [1.0, 2.0, 3.0]
    w = [0.3, 0.5, 1.0]
    C = 3.2
    x = MOI.add_variables(optimizer, length(c))
    MOI.set(        optimizer,
        MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(),
        MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(c, x), 0.0) )

    MOI.set(optimizer, MOI.ObjectiveSense(), MOI.MAX_SENSE)
    MOI.add_constraint(
        optimizer,
        MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(w, x), 0.0),
        MOI.LessThan(C) )
    for x_i in x
        MOI.add_constraint(optimizer, x_i, MOI.ZeroOne())
    end
    MOI.optimize!(optimizer)


    xo = MOI.get(optimizer, MOI.VariablePrimal(), x)
    print(optimizer)
    tex = MOI.Utilities.latex_formulation(optimizer)

```

in the following latex output: `{Float64}` should be `\{Float64\}`  

```
$$ \begin{aligned}
\max\quad & 0.0 + 1.0 v_{1} + 2.0 v_{2} + 3.0 v_{3} \\
\text{Subject to}\\
 & \text{ScalarAffineFunction{Float64}-in-LessThan{Float64}} \\
 & 0.0 + 1.0 v_{3} + 0.5 v_{2} + 0.3 v_{1} \le 3.2 \\
 & \text{VariableIndex-in-ZeroOne} \\
 & v_{1} \in \{0, 1\} \\
 & v_{2} \in \{0, 1\} \\
 & v_{3} \in \{0, 1\} \\
\end{aligned} $$
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2140

### CODE REVIEW

File: src/Utilities/print.jl [hunk 1]
```diff
@@ -575,7 +576,9 @@ function _print_model(
     println(io, "\\text{Subject to}\\\\")
     for (F, S) in MOI.get(model, MOI.ListOfConstraintTypesPresent())
         if options.print_types
-            println(io, " & \\text{$(_drop_moi(F))-in-$(_drop_moi(S))} \\\\")
+            f_str = _escape_braces(_drop_moi(F))
+            s_tr = _escape_braces(_drop_moi(S))
```
Comment (odow) [inline src/Utilities/print.jl:580]:
```suggestion
            s_str = _escape_braces(_drop_moi(S))
```
