### PR TITLE
[FileFormats.MPS] fix writing duplicate bounds for binary variables

### LINKED ISSUE #2425: [FileFormats.MPS] Problem when reading generated MPS with CPLEX
When a binary variable is fixed, the generated MPS cannot be read with CPLEX due to `'FX' bound type illegal when prior bound given.`

```julia
using JuMP
m = Model()
@variable(m, foo, Bin)
fix(foo, 1)
write_to_file(m, "mwe.mps")
```

`mwe.mps` file content:
```
NAME          
ROWS
 N  OBJ
COLUMNS
    MARKER    'MARKER'                 'INTORG'
    foo       OBJ       0
RHS
RANGES
BOUNDS
 BV bounds    foo
 FX bounds    foo       1
ENDATA
```

Then in CPLEX:
```
CPLEX> read mwe.mps
Selected objective sense:  MINIMIZE
Selected objective  name:  OBJ
Selected bound      name:  bounds
CPLEX Error  1454: Line 11: 'FX' bound type illegal when prior bound given.
No file read.
```

Removing `BV bounds    foo` works. If the variable is fixed, the fact that it is a binary variable should not be stated anymore in the MPS file.

### PR DESCRIPTION
**Pull request by odow**
Closes #2425

### CODE REVIEW

File: test/FileFormats/MPS/MPS.jl [hunk 1]
```diff
@@ -11,9 +11,36 @@ using Test
...
+            @testset "$name" begin
+                getfield(@__MODULE__, name)()
+            end
+        end
+    end
+    sleep(1.0)  # Allow time for unlink to happen.
+    rm(MPS_TEST_FILE, force = true)
+    return
+end
+
```
Comment (odow) [inline test/FileFormats/MPS/MPS.jl:31]:
```suggestion
```
