### PR TITLE
[FileFormats.LP] fix reading file with free variable and explicit bounds

### LINKED ISSUE #2223: [FileFormats.LP] more parsing issues
This is on 1.18.0:

```
LP file:
maximize 
obj: 3 x1 + x2 + 5 x3 + x4 
subject to 
c1:  3 x1 + x2 + 2 x3 = 30 
c2:  2 x1 + x2 + 3 x3 + x4 >= 15 
c3:  2 x2 + 3 x4 <= 25 
bounds 
 -infinity <= x1 <= +infinity 
 -10 <= x2 <= 10 
 0 <= x3 <= +infinity 
 10 <= x4 <= +infinity 
end

Parsed Bounds:
0.0 <= x1 <= Inf
x2
0.0 <= x3
10.0 <= x4
```

So x1's lower bound is erroneously set to zero and upper bound isn't dropped (does that matter?), while x2's upper and lower bounds both get dropped.

Code to reproduce:

```julia
import MathOptInterface

const MOI = MathOptInterface

lpfile = """
maximize 
obj: 3 x1 + x2 + 5 x3 + x4 
subject to 
c1:  3 x1 + x2 + 2 x3 = 30 
c2:  2 x1 + x2 + 3 x3 + x4 >= 15 
c3:  2 x2 + 3 x4 <= 25 
bounds 
 -infinity <= x1 <= +infinity 
 -10 <= x2 <= 10 
 0 <= x3 <= +infinity 
 10 <= x4 <= +infinity 
end
"""

println("LP file:\n", lpfile, "\nParsed Bounds:")

io = IOBuffer(lpfile)
m = MOI.FileFormats.Model(format = MOI.FileFormats.FORMAT_LP)
read!(io, m)

for v in MOI.get(m, MOI.ListOfVariableIndices())

    varname = MOI.get(m, MOI.VariableName(), v)
    c_lb = MOI.ConstraintIndex{MOI.VariableIndex, MOI.GreaterThan{Float64}}(v.value)
    c_ub = MOI.ConstraintIndex{MOI.VariableIndex, MOI.LessThan{Float64}}(v.value)

    if MOI.is_valid(m, c_lb)
        lb = MOI.get(m, MOI.ConstraintSet(), c_lb)
        print(lb.lower, " <= ")
    end
    
    print(varname)

    if MOI.is_valid(m, c_ub)
        ub = MOI.get(m, MOI.ConstraintSet(), c_ub)
        print(" <= ", ub.upper)
    end

    println()

end
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2223

We didn't handle the case in which `-infinity <= x <= infinity` was used instead of `x free`. 

But I've also refactored the reading and writing of variable bounds to explicitly write both bounds on a single line with `-infinity`.

### CODE REVIEW

File: src/FileFormats/LP/LP.jl [hunk 1]
```diff
@@ -375,19 +366,31 @@ function Base.write(io::IO, model::Model)
...
+    CI = MOI.ConstraintIndex{MOI.VariableIndex,MOI.ZeroOne}
+    for x in MOI.get(model, MOI.ListOfVariableIndices())
+        lb, ub = MOI.Utilities.get_bounds(model, Float64, x)
+        if lb == -Inf && ub == Inf
+            if MOI.is_valid(model, CI(x.value))
+                # If a variable is binary, it should not be listed as `free` in
+                # the bounds section.
+                continue
+            end
+            print(io , variable_names[x], " free")
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:378]:
```suggestion
            print(io, variable_names[x], " free")
```

File: src/FileFormats/LP/LP.jl [hunk 2]
```diff
@@ -375,19 +366,31 @@ function Base.write(io::IO, model::Model)
...
+        elseif lb == ub
+            print(io , variable_names[x], " = ")
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:380]:
```suggestion
            print(io, variable_names[x], " = ")
```

File: test/FileFormats/LP/LP.jl [hunk 3]
```diff
@@ -942,6 +940,43 @@ function test_read_newline_breaks()
...
+    bounds
+    -infinity <= x1 <= +infinity
+    -infinity <= x2 <= 1
+    -infinity <= x3 <= -1
+    -1 <= x4 <= +infinity
+    1 <= x5 <= +infinity
+    -1 <= x6 <= 1
+    1 <= x7 <= 1
+    end
+    """);
```
Comment (odow) [inline test/FileFormats/LP/LP.jl:957]:
```suggestion
    """)
```
