### PR TITLE
Fix and add test for throwing UnsupportedSubmittable

### LINKED ISSUE #1357: bug with error throwing
[This throw](https://github.com/jump-dev/MathOptInterface.jl/blob/ce19dce9147a8040d8582c79179b541b64e1ce31/src/attributes.jl#L472) does not provide an error message, where `UnsupportedSubmittable` requires one.

### PR DESCRIPTION
**Pull request by odow**
Closes #1357

### CODE REVIEW

File: src/attributes.jl [hunk 1]
```diff
@@ -469,7 +469,12 @@ function submit(model::ModelLike, sub::AbstractSubmittable, args...)
             ),
         )
     else
-        throw(UnsupportedSubmittable(sub))
+        throw(
+            UnsupportedSubmittable(
+                sub,
+                "submit(::$(typeof(model)),::$(typeof(sub))) is not supported.",
```
Comment (blegat) [inline src/attributes.jl:475]: Missing a space after the comma
