### PR TITLE
[FileFormats] fix default lower bound in LP reader

### LINKED ISSUE #1809: FileFormats.LP: default lower bounds not added
This lp file is solved succesfully with the Gurobi direct CLI parser

```
✔ ~/cache/PowerSimulationsTPWRS gurobi_cl "Model.lp"
Using license file /Users/jdlara/gurobi.lic
Set parameter LogFile to value gurobi.log
Academic license - for non-commercial use only - expires 2022-07-19

Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (mac64)
Copyright (c) 2020, Gurobi Optimization, LLC

Read LP format model from file /Users/jdlara/cache/PowerSimulationsTPWRS/PLEXOS-5-BUS/Model.lp
Reading time = 0.01 seconds
: 1450 rows, 1248 columns, 4126 nonzeros
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1450 rows, 1248 columns and 4126 nonzeros
Model fingerprint: 0xd5afd6df
Variable types: 1128 continuous, 120 integer (0 binary)
Coefficient statistics:
  Matrix range     [2e-01, 6e+02]
  Objective range  [1e+01, 1e+06]
  Bounds range     [1e+00, 4e+03]
  RHS range        [1e+00, 1e+03]
Presolve removed 960 rows and 934 columns
Presolve time: 0.01s
Presolved: 490 rows, 314 columns, 1615 nonzeros
Variable types: 165 continuous, 149 integer (149 binary)

Root relaxation: objective 3.230007e+05, 206 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 323000.729    0   27          - 323000.729      -     -    0s
H    0     0                    325542.11138 323000.729  0.78%     -    0s
H    0     0                    323318.31709 323000.729  0.10%     -    0s
     0     0 323244.171    0   21 323318.317 323244.171  0.02%     -    0s

Explored 1 nodes (215 simplex iterations) in 0.04 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 323318 325542 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.233183170895e+05, best bound 3.233183170895e+05, gap 0.0000%
```

If I parse the file with JuMP and solve with JuMP, the solve fails 

```julia

using JuMP
model = read_from_file("Model.lp")
set_optimizer(model, () -> Gurobi.Optimizer())
optimize!(model)
````

results in: 

```
Academic license - for non-commercial use only - expires 2022-07-19
Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (mac64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1450 rows, 1248 columns and 4126 nonzeros
Model fingerprint: 0x654ef39f
Variable types: 1128 continuous, 120 integer (0 binary)
Coefficient statistics:
  Matrix range     [2e-01, 6e+02]
  Objective range  [1e+01, 1e+06]
  Bounds range     [1e+00, 4e+03]
  RHS range        [1e+00, 1e+03]
Presolve removed 10 rows and 485 columns
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.00 seconds
Thread count was 1 (of 8 available processors)

Solution count 0

Model is infeasible or unbounded
Best objective -, best bound -, gap -

User-callback calls 22, time in user-callback 0.00 sec
```

Here is the LP file 

[Model.lp.zip](https://github.com/jump-dev/JuMP.jl/files/8523355/Model.lp.zip)

### PR DESCRIPTION
**Pull request by odow**
Closes #1809. The LP reader is still immature compared to the other formats.

### CODE REVIEW

File: src/FileFormats/LP/LP.jl [hunk 1]
```diff
@@ -629,17 +635,36 @@ function _parse_section(
...
         MOI.add_constraint(model, x, MOI.Interval(lb, ub))
     elseif -Inf < lb
+        _delete_default_lower_bound_if_present(model, cache, x)
         MOI.add_constraint(model, x, MOI.GreaterThan(lb))
     else
+        if ub < 0
+            # We only need to delete the default lower bound if the upper bound
+            # is less than 0.
+            _delete_default_lower_bound_if_present(model, cache, x)
+            MOI.delete(model, c)
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:651]:
```suggestion
```
