### PR TITLE
[Utilities] Re-enable allocation test from #2018

### LINKED ISSUE #2017: Test problems on nightly
Recent jobs have been failing in different ways:

* Segfault https://github.com/jump-dev/MathOptInterface.jl/actions/runs/3261321958/jobs/5355955760
* Suprious allocations https://github.com/jump-dev/MathOptInterface.jl/actions/runs/3255175420/jobs/5344217939

I've been trying, without much luck, to reproduce the segfault locally. The allocations are a change in sorting: https://github.com/JuliaLang/julia/pull/45222

### PR DESCRIPTION
**Pull request by odow**
Tracking to see if #2017 changed.

But I don't expect it to have. This is a regression introduced by https://github.com/JuliaLang/julia/pull/45222.

Closes #2017

### CODE REVIEW

File: test/Utilities/functions.jl [hunk 1]
```diff
@@ -1058,7 +1058,9 @@ function _test_canonicalization(
     @test MOI.Utilities.canonical(g) !== g
     # There are some changes to sorting in Julia v1.9 that now mean sorting
     # allocates.
-    # @test @allocated(MOI.Utilities.canonicalize!(f)) == 0
+    if VERSION < v"1.9"
```
Comment (odow) [inline test/Utilities/functions.jl:1061]:
```suggestion
    if VERSION < v"1.9.0-DEV"
```

File: src/Utilities/functions.jl [hunk 2]
```diff
@@ -833,7 +833,7 @@ function _sort_and_compress!(x::Vector)
     if length(x) == 0
         return
     end
-    sort!(x; by = MOI.term_indices)
+    sort!(x, QuickSort, Base.Order.ord(isless, MOI.term_indices, false))
```
Comment (odow) [inline src/Utilities/functions.jl:836]:
```suggestion
    sort!(x, InsertionSort, Base.Order.ord(isless, MOI.term_indices, false))
```

File: test/Utilities/functions.jl [hunk 3]
```diff
@@ -1058,7 +1058,9 @@ function _test_canonicalization(
     @test MOI.Utilities.canonical(g) !== g
     # There are some changes to sorting in Julia v1.9 that now mean sorting
     # allocates.
-    # @test @allocated(MOI.Utilities.canonicalize!(f)) == 0
+    if VERSION < v"1.9.0-DEV"
```
Comment (odow) [inline test/Utilities/functions.jl:1061]:
```suggestion
    if true # VERSION < v"1.9.0-DEV"
```

**Comment by odow** [comment]
@blegat I've changed to use InsertionSort since QuickSort allocates on Julia 1.9. Thoughts?

**Comment by odow** [comment]
Merging because insertion sort is probably a better choice here anyway. We mostly work with small arrays because most constraints are sparse and have few terms.
