### PR TITLE
[Utilities] fix stackoverflow in operate(+,...) with many arguments

### LINKED ISSUE #2284: `MOI.Utilities.operate` StackOverflowError
The following returns a `StackOverflowError` due to deep recursion:

```julia
x = [i + i*MOI.VariableIndex(i) for i in 1:1000]
MOI.Utilities.operate(+, Int, x...)
```
`operate` is used in [SolverAPI.jl](https://github.com/RelationalAI/SolverAPI.jl/blob/ec5d3292fa809a8c663b0a57852e656fa5f43936/src/SolverAPI.jl#L487C37-L487C37) to convert from SNF to SAF or SQF when possible.

The proposed fix is to rewrite the following
https://github.com/jump-dev/MathOptInterface.jl/blob/53ec2693c8280d0e3f53336142c8739298eef0e5/src/Utilities/operate.jl#L323-L327

as (credit to @bachdavi for this solution):
```julia
function operate(::typeof(+), ::Type{T}, args...) where {T<:Number}
    operate_plus(accum, x) = MOI.Utilities.operate!(+, T, accum, x)
    return reduce(operate_plus, args)
end
```

Some tests shown below (Note: `operate2` is the new form of `operate` above):
```julia
# 100 ScalarAffineFunction args
julia> x = [i + i*MOI.VariableIndex(i) for i in 1:100];

julia> @time MOIU.operate(+, Int, x...);
  0.000200 seconds (199 allocations: 46.078 KiB)

julia> @time MOIU.operate2(+, Int, x...);
  0.000030 seconds (7 allocations: 6.797 KiB)
#--------------------------------------------------
# 1000 ScalarAffineFunction{Int} args  
julia> x = [i + i*MOI.VariableIndex(i) for i in 1:1000];

julia> @time MOIU.operate(+, Int, x...);
ERROR: StackOverflowError:

julia> @time MOIU.operate2(+, Int, x...);
  0.000093 seconds (9 allocations: 74.734 KiB) 
#--------------------------------------------------
# 1000 ScalarAffineFunction{Float64} args
julia> x = [i + i*MOI.VariableIndex(i) for i in 1.0:1000.0];

julia> @time MOIU.operate2(+, Float64, x...);
  0.000116 seconds (9 allocations: 74.734 KiB)
#--------------------------------------------------  
# 1000 ScalarQuadraticFunction args
julia> x = [i + i*MOI.VariableIndex(i)*MOI.VariableIndex(i) for i in 1:1000];

julia> @time MOIU.operate(+, Int, x...);
ERROR: StackOverflowError:

julia> @time MOIU.operate2(+, Int, x...);
  0.000105 seconds (5 allocations: 127.562 KiB)
#--------------------------------------------------  
# 1000 mixed aff and quad args
julia> x = [i + i*MOI.VariableIndex(i)*MOI.VariableIndex(i) for i in 1:500];

julia> y = [i + i*MOI.VariableIndex(i) for i in 1:500];

julia> z = vcat(x,y);

julia> @time MOIU.operate(+, Int, z...);
ERROR: StackOverflowError:

julia> @time MOIU.operate2(+, Int, z...);
  0.000126 seconds (6 allocations: 102.750 KiB)
```

Moving to higher number of affine function args:
image

Happy to submit a PR to MOI if desired.

### PR DESCRIPTION
**Pull request by odow**
Closes #2284

### CODE REVIEW

File: src/Utilities/operate.jl [hunk 1]
```diff
@@ -323,7 +323,12 @@ end
 ### 1c: operate(+, T, args...)
 
 function operate(::typeof(+), ::Type{T}, f, g, h, args...) where {T<:Number}
-    return operate!(+, T, operate(+, T, f, g), h, args...)
+    ret = operate(+, T, f, g)
+    operate!(+, T, ret, h)
```
Comment (odow) [inline src/Utilities/operate.jl:327]:
```suggestion
    ret = operate!(+, T, ret, h)
```

File: src/Utilities/operate.jl [hunk 2]
```diff
@@ -1167,8 +1172,13 @@ end
 
 ### 1c: operate!(+, T, args...)
 
-function operate!(op::typeof(+), ::Type{T}, f, g, h, args...) where {T<:Number}
-    return operate!(+, T, operate!(op, T, f, g), h, args...)
+function operate!(::typeof(+), ::Type{T}, f, g, h, args...) where {T<:Number}
+    ret = operate!(+, T, f, g)
+    operate!(+, T, ret, h)
```
Comment (odow) [inline src/Utilities/operate.jl:1177]:
```suggestion
    ret = operate!(+, T, ret, h)
```
