### PR TITLE
[Bridges] fix UnsupportedAttribute in function_conversion.jl

### LINKED ISSUE #1758: Unsupported attribute fails with function conversion bridge
This:
https://github.com/jump-dev/MathOptInterface.jl/blob/03640abedfeb1716b62ab930d091e7013abc4c73/src/Test/test_model.jl#L623-L626
fails with:
```
Test Failed at /home/blegat/.julia/dev/SDPT3/test/tmp.jl:26
  Expression: MOI.optimize!(model, MOI.Test.BadConstraintAttributeModel(T))
    Expected: MathOptInterface.UnsupportedAttribute
      Thrown: ArgumentError
ERROR: LoadError: There was an error during testing
in expression starting at /home/blegat/.julia/dev/SDPT3/test/tmp.jl:65
```
The `ArgumentError` that is thrown is:
```
ERROR: LoadError: ArgumentError: Bridge of type `MathOptInterface.Bridges.Constraint.ScalarFunctionizeBridge{Float64, MathOptInterface.EqualTo{Float64}}` does not support setting the attribute `MathOptInterface.Test.UnknownConstraintAttribute()` because `MOIB.Constraint.invariant_under_function_conversion(MathOptInterface.Test.UnknownConstraintAttribute())` returns `false`.
Stacktrace:
  [1] set(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPT3.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, attr::MathOptInterface.Test.UnknownConstraintAttribute, bridge::MathOptInterface.Bridges.Constraint.ScalarFunctionizeBridge{Float64, MathOptInterface.EqualTo{Float64}}, value::Int64)
    @ MathOptInterface.Bridges.Constraint ~/.julia/packages/MathOptInterface/IIN1o/src/Bridges/Constraint/function_conversion.jl:42
...
```

Detected while going from DeprecatedTest to Test in https://github.com/jump-dev/SDPT3.jl/pull/15

### PR DESCRIPTION
**Pull request by odow**
Closes #1758

### CODE REVIEW

**Review by blegat — APPROVED** [review]

File: src/Bridges/Constraint/function_conversion.jl [hunk 1]
```diff
@@ -16,7 +16,8 @@ function MOI.get(
         return MOI.get(model, attr, bridge.constraint)
     else
         throw(
-            ArgumentError(
+            MOI.UnsupportedAttribute(
+                attr,
                 "Bridge of type `$(typeof(bridge))` does not support accessing the attribute `$attr` because `MOIB.Constraint.invariant_under_function_conversion($attr)` returns `false`.",
```
Comment (odow) [inline src/Bridges/Constraint/function_conversion.jl:21]:
```suggestion
                "Bridge of type `$(typeof(bridge))` does not support getting the attribute `$attr` because `MOIB.Constraint.invariant_under_function_conversion($attr)` returns `false`.",
```
