### PR TITLE
[FileFormats.LP] more fixes from QPLIB

### LINKED ISSUE #2045: [Fileformats.LP] Few more errors:
I got few more errors, I pasted below a representative example for each.
The `Name contains with invalid character: <=` ones should all be the same I feel.

```julia
julia> MOI.read_from_file(o, "QPLIB_0032.lp.gz")
ERROR: Name contains with invalid character: <=
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] _get_variable_from_name(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, name::String)
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:477
  [3] _parse_function(f::MathOptInterface.ScalarAffineFunction{Float64}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, tokens::Vector{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:582
  [4] _parse_section(#unused#::Val{:constraints}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:705
  [5] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:933
  [6] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
  [7] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
  [8] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
  [9] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [10] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [11] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [12] top-level scope
    @ REPL[3]:1
```

```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_0678.lp.gz")
ERROR: ArgumentError: cannot parse "x739" as Float64
Stacktrace:
  [1] _parse_failure(T::Type, s::String, startpos::Int64, endpos::Int64) (repeats 2 times)
    @ Base ./parse.jl:373
  [2] #tryparse_internal#403
    @ ./parse.jl:369 [inlined]
  [3] tryparse_internal
    @ ./parse.jl:367 [inlined]
  [4] #parse#404
    @ ./parse.jl:379 [inlined]
  [5] parse
    @ ./parse.jl:379 [inlined]
  [6] _parse_float(token::String)
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:736
  [7] _parse_section(#unused#::Val{:bounds}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:772
  [8] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:933
  [9] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
 [10] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
 [11] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
 [12] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [13] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [14] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [15] top-level scope
    @ REPL[4]:1
```

```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_0681.lp.gz")
ERROR: Name contains with invalid character: =
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] _get_variable_from_name(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, name::String)
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:477
  [3] _parse_function(f::MathOptInterface.ScalarAffineFunction{Float64}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, tokens::Vector{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:582
  [4] _parse_section(#unused#::Val{:constraints}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:705
  [5] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:933
  [6] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
  [7] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
  [8] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
  [9] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [10] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [11] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [12] top-level scope
    @ REPL[5]:1
```

and a fairly mysterious one:
```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_10007.lp.gz")
ERROR: zlib error: <no message> (code: -5)
Stacktrace:
  [1] changemode!(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, newmode::Symbol)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:732
  [2] callprocess(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, inbuf::TranscodingStreams.Buffer, outbuf::TranscodingStreams.Buffer)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:658
  [3] fillbuffer(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}; eager::Bool)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:586
  [4] fillbuffer
    @ /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:573 [inlined]
  [5] eof(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream})
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:191
  [6] eof(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream})
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:189
  [7] _readline
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:949 [inlined]
  [8] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:926
  [9] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
 [10] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
 [11] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
 [12] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [13] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [14] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [15] top-level scope
    @ REPL[6]:1
```

```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_2073.lp.gz")
ERROR: Name contains with invalid character: >=
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] _get_variable_from_name(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, name::String)
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:477
  [3] _parse_function(f::MathOptInterface.ScalarAffineFunction{Float64}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, tokens::Vector{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:582
  [4] _parse_section(#unused#::Val{:constraints}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:705
  [5] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:933
  [6] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
  [7] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
  [8] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
  [9] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [10] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [11] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [12] top-level scope
    @ REPL[7]:1
```

```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_3729.lp.gz")
ERROR: ArgumentError: cannot parse "x2" as Float64
Stacktrace:
  [1] _parse_failure(T::Type, s::String, startpos::Int64, endpos::Int64) (repeats 2 times)
    @ Base ./parse.jl:373
  [2] #tryparse_internal#403
    @ ./parse.jl:369 [inlined]
  [3] tryparse_internal
    @ ./parse.jl:367 [inlined]
  [4] #parse#404
    @ ./parse.jl:379 [inlined]
  [5] parse
    @ ./parse.jl:379 [inlined]
  [6] _parse_float(token::String)
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:736
  [7] _parse_section(#unused#::Val{:bounds}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:772
  [8] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:933
  [9] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
 [10] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
 [11] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
 [12] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [13] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [14] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [15] top-level scope
    @ REPL[8]:1
```

```julia
julia> MOI.read_from_file(o, "/nfs/optimi/kombadon/MINLP/instances/qplib/lp/QPLIB_8547.lp.gz")
ERROR: zlib error: <no message> (code: -5)
Stacktrace:
  [1] changemode!(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, newmode::Symbol)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:732
  [2] callprocess(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, inbuf::TranscodingStreams.Buffer, outbuf::TranscodingStreams.Buffer)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:658
  [3] fillbuffer(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}; eager::Bool)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:586
  [4] fillbuffer
    @ /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:573 [inlined]
  [5] eof(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream})
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:191
  [6] eof(stream::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream})
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:189
  [7] _readline
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:949 [inlined]
  [8] read!(io::TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, IOStream}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
    @ MathOptInterface.FileFormats.LP /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/LP/LP.jl:926
  [9] #11
    @ /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:121 [inlined]
 [10] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::Type{TranscodingStreams.TranscodingStream{CodecZlib.GzipDecompressor, S} where S<:IO}, ::String, ::String)
    @ TranscodingStreams /scratch/opt/mbesanco/.julia/packages/TranscodingStreams/DYpJd/src/stream.jl:164
 [11] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.Gzip)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:224
 [12] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/utils.jl:251
 [13] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
    @ MathOptInterface.FileFormats /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/FileFormats/FileFormats.jl:120
 [14] read_from_file(model::MathOptInterface.Utilities.Model{Float64}, filename::String)
    @ MathOptInterface /scratch/opt/mbesanco/.julia/dev/MathOptInterface/src/MathOptInterface.jl:152
 [15] top-level scope
    @ REPL[9]:1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2045 

cc @matbesancon 

This fixes some of the issues:
```julia
julia> import Downloads

julia> function read_qplib(num)
           num = lpad(num, 4, '0')
           io = IOBuffer()
           Downloads.download("https://qplib.zib.de/lp/QPLIB_$(num).lp", io)
           seekstart(io)
           model = MOI.FileFormats.LP.Model()
           Base.read!(io, model)
           return model
       end
read_qplib (generic function with 1 method)

julia> read_qplib(0032)
A .LP-file model

julia> read_qplib(0678)
A .LP-file model

julia> read_qplib(0681)
A .LP-file model

julia> read_qplib(2073)
A .LP-file model

julia> read_qplib(3729)
A .LP-file model
```

but it doesn't fix the zlib errors (which I think are just because the files are so large?)

### CODE REVIEW

**Comment by odow** [comment]
Tested locally with all of QPLIB, and things are passing (once https://github.com/jump-dev/MathOptInterface.jl/pull/2047 is merged).

File: src/FileFormats/LP/LP.jl [hunk 1]
```diff
@@ -758,27 +757,50 @@ function _parse_section(
...
+            elseif _is_greater_than(tokens[2])
+                # bound >= name
+                ub = lhs
+                # LP files have default lower bounds of 0, unless the upper
+                # bound is less than 0.
+                lb = ub > 0.0 ? 0.0 : -Inf
+            elseif _is_equal_to(tokens[2])
+                lb = ub = lhs
+            else
+                error("Unable to parse bound due to invalid inequalities: $(line)")
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:802]:
```suggestion
                error(
                    "Unable to parse bound due to invalid inequalities: $(line)",
                )
```

File: src/FileFormats/LP/LP.jl [hunk 2]
```diff
@@ -758,27 +757,50 @@ function _parse_section(
...
+                # LP files have default lower bounds of 0, unless the upper
+                # bound is less than 0.
+                lb = ub > 0.0 ? 0.0 : -Inf
+            elseif _is_greater_than(tokens[2])
+                # name >= bound
+                lb = rhs
+            elseif _is_equal_to(tokens[2])
+                lb = ub = rhs
+            else
+                error("Unable to parse bound due to invalid inequalities: $(line)")
```
Comment (odow) [inline src/FileFormats/LP/LP.jl:785]:
```suggestion
                error(
                    "Unable to parse bound due to invalid inequalities: $(line)",
                )
```

**Comment by matbesancon** [comment]
awesome thank you!
