### PR TITLE
[Bridges] fix ordering of variables returned by LazyBridgeOptimizer

### LINKED ISSUE #2693: Add tests for MOI.add_constrained_variables
Mosek is a bit of a a special case because they tread PSD matrix variables so differently, but this type of bug really shouldn't have gone undetected in our tests

https://github.com/jump-dev/MosekTools.jl/pull/180

### PR DESCRIPTION
**Pull request by odow**
There were a number of trivial bugs in MosekTools.jl because we didn't have these tests.

Closes #2693

This needs solver-tests.yml. I think it might break Ipopt: https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14044969174

### CODE REVIEW

File: src/Test/test_conic.jl [hunk 1]
```diff
@@ -7219,3 +7219,115 @@ function setup_test(
...
+function test_add_constrained_PositiveSemidefiniteConeTriangle_VariableName(
+    model::MOI.ModelLike,
+    config::Config{T},
+) where {T<:Real}
+    @requires MOI.supports_add_constrained_variables(
+        model,
+        MOI.PositiveSemidefiniteConeTriangle,
+    )
+    @requires MOI.supports(model, MOI.VariableName(), MOI.VariableIndex)
+    X, _ = MOI.add_constrained_variables(model, set)
```
Comment (odow) [inline src/Test/test_conic.jl:7297]:
```suggestion
    set = MOI.PositiveSemidefiniteConeTriangle(2)
    X, _ = MOI.add_constrained_variables(model, set)
```

File: src/Test/test_conic.jl [hunk 2]
```diff
@@ -7219,3 +7219,115 @@ function setup_test(
...
+function test_add_constrained_PositiveSemidefiniteConeTriangle_VariablePrimalStart(
+    model::MOI.ModelLike,
+    config::Config{T},
+) where {T<:Real}
+    @requires MOI.supports_add_constrained_variables(
+        model,
+        MOI.PositiveSemidefiniteConeTriangle,
+    )
+    @requires MOI.supports(model, MOI.VariablePrimalStart(), MOI.VariableIndex)
+    X, _ = MOI.add_constrained_variables(model, set)
```
Comment (odow) [inline src/Test/test_conic.jl:7320]:
```suggestion
    set = MOI.PositiveSemidefiniteConeTriangle(2)
    X, _ = MOI.add_constrained_variables(model, set)
```

File: src/Test/test_conic.jl [hunk 3]
```diff
@@ -7219,3 +7219,117 @@ function setup_test(
...
+) where {T<:Real}
+    @requires MOI.supports_add_constrained_variables(
+        model,
+        MOI.PositiveSemidefiniteConeTriangle,
+    )
+    @requires MOI.supports(model, MOI.VariableName(), MOI.VariableIndex)
+    set = MOI.PositiveSemidefiniteConeTriangle(2)
+    X, _ = MOI.add_constrained_variables(model, set)
+    MOI.set(model, MOI.VariableName(), X[1], "x")
+    @test MOI.get(model, MOI.VariablePrimalStart(), X[1]) == "x"
```
Comment (odow) [inline src/Test/test_conic.jl:7300]:
```suggestion
    @test MOI.get(model, MOI.VariableName(), X[1]) == "x"
```
